In [1]:
import numpy as np


In [3]:
# --- 1. Create arrays ---
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)
matrix = np.random.randn(3, 4)   # shape (3, 4)

print("Shape:", matrix.shape)
print("Dtype:", matrix.dtype)


Shape: (3, 4)
Dtype: float64


In [4]:

# --- 2. Reshape & transpose ---
reshaped = matrix.reshape(4, 3)
transposed = matrix.T             # shape (4, 3)

In [5]:
# --- 3. Broadcasting example ---
x = np.array([[1],[2],[3]])       # shape (3, 1)
y = np.array([10, 20, 30])        # shape (3,)
print(x + y)                      # broadcasts to (3, 3)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [6]:
# --- 4. Vectorized ops (no loops!) ---
def dot_product(a, b):
    return np.dot(a, b)

def normalize(v):
    return v / np.linalg.norm(v)

def matrix_multiply(A, B):
    return A @ B                  # or np.matmul(A, B)


In [7]:
# --- 5. Test your functions ---
v = np.array([3.0, 4.0])
print("Normalized:", normalize(v))  # [0.6, 0.8]

A = np.random.randn(2, 3)
B = np.random.randn(3, 2)
print("MatMul shape:", matrix_multiply(A, B).shape)  # (2, 2)

Normalized: [0.6 0.8]
MatMul shape: (2, 2)
